### ISSUE TITLE
daligner error in read correction step

### ISSUE THREAD

**Issue by compbiochem** [PacificBiosciences/FALCON#21] opened 2015-02-20 17:57 UTC
I have been experiencing and issue where during the raw read error correction phase, when the initial d_* (daligner) jobs are running, the vast majority will complete without issue, but some small number never really start.  When I check the individual log file (ex: 0-rawreads/job_d72b16ef/rj_d72b16ef.log)
all I see is:

Fri Feb 20 09:20:28 PST 2015
daligner: System error, read failed!

I have tried many different avenues and can't find the cause of the error.

**Comment by pb-jchin** [comment] 2015-02-20 18:16
Have you try to run the `rj_*.sh` to see what exact happens?  There might be some files corrupted...

**Comment by compbiochem** [comment] 2015-02-20 18:18
running the individual rj*.sh script produces the exact same error message

**Comment by pb-jchin** [comment] 2015-02-20 18:20
Can you cut and past about 20 lines where the error happens in the log?

**Comment by compbiochem** [comment] 2015-02-20 18:23
the only lines in the individual log are what you see above: 

Fri Feb 20 09:20:28 PST 2015
daligner: System error, read failed!

from the sge_log folder:

real    0m0.290s
user    0m0.043s
sys     0m0.048s

**Comment by pb-jchin** [comment] 2015-02-20 18:29
ok, you sequence db might be corrupted. You should try if you can run DBstat and DBshow on your raw_reads.db.

**Comment by compbiochem** [comment] 2015-02-20 20:44
DBstat seems to run fine, but DBshow produces the error:

DBshow: System error, read failed!

**Comment by pb-jchin** [comment] 2015-02-20 21:20
Can you check with a subset of data to see if the database is created such that you can run both DBstat and DBshow?

**Comment by compbiochem** [comment] 2015-02-21 03:26
I cut my data down by a factor of ~20 and still receive the same error.  Albeit only for one of the eleven jobs.

**Comment by pb-jchin** [comment] 2015-02-21 03:41
Some jobs did go through, the DB should be ok. two things to check : (1) the file size of the las files (also check with LAshow to see if you can see the overlap data and (2) is the log of the failure jobs still empty?

**Comment by compbiochem** [comment] 2015-02-22 20:18
The .las files are about 2-2.5 mb for the jobs that do complete, and I am able to see the overlap data just fine.  The log of the failure jobs still only contains:

Fri Feb 20 16:58:26 PST 2015
daligner: System error, read failed!

and there are no .las files present in the directory.

**Comment by pb-jchin** [comment] 2015-02-22 22:08
ok. It seems everything works except one block. In this case, I would suggest trying to make different size of block.  There might be some wired boundary condition causing such problem.  Try using different -s parameter to chunk the data into different block partition.  If this is not working, I might have to look the data if necessary.

**Comment by compbiochem** [comment] 2015-02-23 15:39
I have tried different -s sizes (350, 400, 1000) and have not had any luck - still getting the same error.  Is there another -s size I should be trying or any other parameter changes?

**Comment by flowers9** [comment] 2015-02-23 16:16
I modified DB.h to include file and line in the SYSTEM_ERROR macro.  The log files consistently showed the error as coming from DB.c, line 1154, which is where DB attempts to read a compressed sequence.  Looking over what reads were being passed to daligner, raw_reads.237 was consistently present.  I checked the m_000237 directory, and it was empty (m_000237 was the last m_* directory).

My guess at this point is that there's an off by one error that shows up when the read count hits particular values, causing the creation of the empty directory and the erroring out of daligner runs against the non-existent reads in that directory.  This wouldn't be so bad except that the failed daligner runs effectively lock process slots, and eventually lead to to running jobs.

**Comment by flowers9** [comment] 2015-02-23 16:52
I've also had this problem.  The bad block is the last block in the db (237 out of 237, in my case).

Just for a bit more info, I added the file and line to SYSTEM_ERROR in DB.h, and it's erroring out on DB.c line 1154.

In my case, DBshow eventually errors out (presumably when it hits the last block), but DBstats works.

**Comment by compbiochem** [comment] 2015-02-23 16:54
Similar for me, DBstat works fine and DBshow eventually errors out after outputting some reads

**Comment by flowers9** [comment] 2015-02-23 16:58
My current guess is that DBsplit has an off by one error that is creating an empty final block in some cases.

**Comment by pb-jchin** [comment] 2015-02-23 17:10
hi, flowers9, do you think you can make a small fasta file that reproduce this? I also been tracking some of the DB code, if it can be reproduced on my side, I might be able to come up with a quick fix. Thanks.

**Comment by flowers9** [comment] 2015-02-23 17:16
I'm working on trying to isolate the issue, yeah.  Was wrong about DBsplit - the error is there after fast2DB sets up the database, and before DBsplit.

**Comment by flowers9** [comment] 2015-02-23 17:34
http://hagsc.org/~flowers/bad_read.fasta

**Comment by flowers9** [comment] 2015-02-23 18:05
In fact, it's looking like 1-2% of the reads in my test run appear to exhibit this problem when tested individually (based on a ~20k read sample set, so far).

**Comment by pb-jchin** [comment] 2015-02-23 18:43
Good, it is confirmed. I will take a look once I get time to trace the code.

fasta2DB -v bad_read bad_read.fasta 
DBsplit -s400 bad_read  #OK
DBstats bad_read #OK

$ DBshow bad_read
>Prolog/1815/0_11537
DBshow: System error, read failed!

**Comment by flowers9** [comment] 2015-02-23 19:23
Looks like the problem is that the actual basepair length != the length specified in the header.  Load_Read (which is what DBshow uses) works properly when I manually force it to use the actual length of the read.

**Comment by flowers9** [comment] 2015-02-23 19:41
Ah, my mistake - it's more like 94% of our reads have this problem, when looked at individually.

**Comment by flowers9** [comment] 2015-02-23 20:02
And, having talked a bit to the people who get the data from the machines, it seems what causes this is that we use some of our own software to trim the fasta files.  Of course, this isn't reflected in the read header, so the read header beg/end no longer match up properly with the read.  I'm planning to modify our software to update the read header to reflect any trimming that gets done, which should solve this problem (at least for us).  I dunno how you want to proceed on your end, but at least having a warning when there's a mismatch between read lengths in basepairs versus headers might be a good idea.

**Comment by pb-jchin** [comment] 2015-02-23 20:07
flowers9, thanks for finding this out.  In the 2nd stage of overlapping, I did similar thing to hack the header. I think ultimately it might be used to have an option for `fasta2db` to ignore the header to generate internal consistent record to avoid crash.  I don't really own the `fasta2db` code but if you have time for a patch, I can integrate to my own repository. I can recommend to Gene to add such option once he has time to work on this. (He is moving a long fast, so he might not likely have time to backport to older code base used here.)

**Comment by flowers9** [comment] 2015-02-23 20:25
Does the read header beg/end info get used anywhere other than calculating the read lengths?  It's be easy to set them to 1/basepairs in read, but I woudln't want to mess anything else up.

**Comment by pb-jchin** [comment] 2015-02-23 21:58
The number is there for identifying the relationship between the subreads to the original sequences. The exact relation is not use in any following process.  It will be OK if such relationship is not important for certain applications.  In the case of assembly, most time it is not necessary to track such information.

**Comment by flowers9** [comment] 2015-02-23 22:18
Okay, I made a quick patch to fasta2DB.c to give it an option to use the actual read length rather than the read header (it's -r).

http://hagsc.org/~flowers/fast2DB.patch

**Comment by flowers9** [comment] 2015-02-23 22:27
Thanks for all the help!

**Comment by pb-jchin** [comment] 2015-02-23 22:34
you patch is pulled: https://github.com/pb-jchin/DAZZ_DB/commit/793373ed5437a81b687ad89e874b61a304d4cdb4 

I will have to modify some of the falcon script to use it.  once I have done that, we can close this issue.

**Comment by pb-jchin** [comment] 2015-02-23 23:00
Modify the default fasta2DB behavior to handle the case where read length != end - beg. This way we don't have to modify fc_run.py for different scenarios. https://github.com/pb-jchin/DAZZ_DB/commit/09cb30930b205f613f22b7cdcf94ebd3f2bc653c 

compbiochem, please pull the update DAZZ_DB from https://github.com/pb-jchin/DAZZ_DB/ and rebuild it to see if that solves your problem.

**Comment by compbiochem** [comment] 2015-02-24 21:43
Thank you both for working out this issue.  In terms of pulling the update and rebuilding, I am hoping you can help me out with an installation issue I have been having at a national computing resource.  When I try to rebuild with:

virtualenv --no-site-packages  --always-copy   $PWD/fc_env
. $PWD/fc_env/bin/activate
git clone https://github.com/cschin/pypeFLOW
cd pypeFLOW
python setup.py install

cd ..
git clone https://github.com/PacificBiosciences/FALCON.git
cd FALCON
python setup.py install

cd ..
git clonehttps://github.com/pb-jchin/DAZZ_DB.git
cd DAZZ_DB/
make
cp DBrm DBshow DBsplit DBstats fasta2DB ../fc_env/bin/

cd ..
git clone https://github.com/pb-jchin/DALIGNER.git
cd DALIGNER
make
cp daligner daligner_p DB2Falcon HPCdaligner LA4Falcon LAmerge LAsort  ../fc_env/bin
cd ..

I see the error, "line 6: /usr/bin/time: No such file or directory" when I try to run the test job for all of the d_* error correction jobs in 0-rawreads.  Apologies, but I didn't do the original install, but some of the folks at this resource want me to prove the update fixes my issue, by doing an install in one my directories.

**Comment by pb-jchin** [comment] 2015-02-24 22:30
compbiochem, please submit to a different issue as this is very different from the original question. (In the mean time, you can safely remove all "/usr/bin/time" in fc_run.py it is used only for benchmarking computational performance and tracking resource usage. A good thing such you might want to request your admin to install it.)

**Comment by flowers9** [comment] 2015-03-02 18:43
Looking through the patched code, I think you still need to change (in fasta2DB.c, line 382)
              if (end-beg >= 0x10000)
to
              if (end-beg >= 0x10000 && rrlen >= 0x10000)
to avoid the edge case where rrlen is less than that, and the subsequent
                  rrlen = 0x10000 - 1;
                  read[rrlen] = '\0';
potentially writes past the end of the read array (in addition to rrlen being set to a value that could cause the original issue to show up again).

**Comment by pb-jchin** [comment] 2015-03-03 00:20
do you mean `if (end-beg >= 0x10000 && rlen >= 0x10000)` ( `rlen` not `rrlen`)?

**Comment by pb-jchin** [comment] 2015-03-13 05:01
flower9, any comment?

**Closed** 2015-04-01 01:06 UTC
Labels: enhancement
