### ISSUE TITLE
Is there an estimate of running time?

### ISSUE THREAD

**Issue by yunfeiguo** [PacificBiosciences/FALCON#44] opened 2015-04-13 05:08 UTC
Dear Dr. Chin,

Is there a way in Falcon to estimate running time? We are running Falcon on a large data set for several days. I think it should have been done based on previous analyses, but it's stilling running (if you use 'top' on compute nodes, you can see DALIGNER is working). Even an estimate on number of remaining jobs would be helpful. 

Thanks!

Best,
Yunfei

**Comment by pb-jchin** [comment] 2015-04-15 22:17
@yunfeiguo , some discussion happens here https://github.com/PacificBiosciences/FALCON/issues/46,
I will mark this issue to be duplicate of that. Please join there for discussion.

**Closed** 2015-04-15 22:17 UTC
Labels: duplicate
