### ISSUE TITLE
what would cause an assembly to have 2x the bases in the genome?

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#400] opened 2016-06-28 15:35 UTC
It is a 3G genome but p_ctg.fa has  6.1GB.  When using 15kb/15kb length cutoffs, I get reasonable numbers.  But when using 10kb/6kb, I get this 6.1GB.  (Or maybe there is some other difference I'm unaware of...  There are 304MB in a_ctg.fa)

**Comment by pb-jchin** [comment] 2016-06-28 16:29
First, we should not exclude the possibility that is can be the biological reality. I don't have the detail information about the project and the nature of the same, so I can not say much about it.

Second, if this is caused by the problem of the algorithms/code. There are a couple of thing you can check.  Internally, FALCON graph-to-layout treats sequences and the corresponded reversed complementary sequences as different entity (with particular symmetry between them). Such redundancy is removed at the end (from graph to contig sequences).  If, for any reason, the code got modified or a bug, the reduction mechanism is not working properly, then you could have 2x amount of contig sequences as output.  However, I have never seen this myself.  You can check this by aligning the assembly results against itself or just do quick search some string and the reverse complementary string in the assembly results at once.   

The other possibility is actually more biological. If the two haplotypes of a diploid are very diversity, you will see twice amount of the genome too.

**Comment by dgordon562** [comment] 2016-06-28 16:38
Thanks, Jason.

**Comment by dgordon562** [comment] 2016-06-28 18:05
Look at this!  Why didn't falcon remove the reverse?  Seems like a serious bug, no?

000000F 51783479        87      51783479        51783480
000000R 51786102        51783654        51786102        51786103
000001F 46231919        103569844       46231919        46231920
000001R 46231515        149801851       46231515        46231516
000002F 39517240        196033454       39517240        39517241
000002R 39542371        235550782       39542371        39542372
000003F 38164756        275093241       38164756        38164757
000003R 38174091        313258085       38174091        38174092
000004F 37453484        351432264       37453484        37453485
000004R 37446286        388885836       37446286        37446287
000005F 37251865        426332210       37251865        37251866
000005R 37253513        463584163       37253513        37253514

**Comment by pb-cdunn** [comment] 2016-06-28 21:26
Nah, that's normal.

**Comment by dgordon562** [comment] 2016-06-28 21:44
So I should just remove all of the *R for which there is a *F ?  If so, perhaps that should be done by falcon?

**Comment by pb-jchin** [comment] 2016-06-28 22:09
what files are you looking? It is a feature as the pair are correct labeled.

**Comment by dgordon562** [comment] 2016-06-28 22:19
p_ctg.fa

**Comment by pb-jchin** [comment] 2016-06-28 22:32
If you don't see "XXXXXXR" before, and you see it now, it means there is some code changes there.  

These couple lines in `graph_to_contig.py` removes the dual contigs:
```
142             if (reverse_end(t0), reverse_end(s0)) in layout_ctg:
143                 continue
144             else:
145                 layout_ctg.add( (s0, t0) )
```

**Comment by dgordon562** [comment] 2016-06-29 17:13
Hi, Jason and Chris,

People here are asking me why I've never seen this problem before in the zillions of assemblies I've done.  What do you think?  And why would changing just the length_cutoff suddenly cause most/all of the contigs to be duplicated?

Thanks!
David

**Comment by pb-jchin** [comment] 2016-06-29 17:14
have you checked the `graph_to_contig.py` code in your library?

**Comment by pb-jchin** [comment] 2016-06-29 17:37
on the other hand, if you verify there are both `*F` and `*R` contigs, you can safely remove the `*R` contigs.  This discussion does make me thinking a little bit.  Technically, if we think genome assembly is assembling the sequences (as simple strings), the forward and reversed-complementary DNA sequences are actually different strings.  For example, the gene sequences have directionality. It may make sense to assemble the forward and reversed-complementary as operated entity.  In the assembly, the "duality" is actually introduced from the overlapping stage.  If we don't overlapping from both orientation, we will generated both the forward and RC contigs as separated sequences and we can merge then at the end. Don't worry about, I won't implement this any time soon. Just some interesting question to think about.

**Comment by pb-jchin** [comment] 2016-06-29 17:57
I can't think of a reason why chasing the length_cutoff will change the layout part of the code. The `graph_to_contig.py` knows nothing about the `length_cutoff` at all.

**Comment by dgordon562** [comment] 2016-06-29 18:07
OK.  Thanks.  It doesn't make sense to us, either, but that's what happened.

**Comment by pb-cdunn** [comment] 2016-06-29 22:54
David, I thought you were looking at a different file. I'll look at this soon. Hopefully it's ok to delete the R contings for now.

**Comment by pb-cdunn** [comment] 2016-06-29 22:54
David, I thought you were looking at a different file. I'll look at this soon. Hopefully it's ok to delete the R contings for now.

**Comment by pb-jchin** [comment] 2016-10-17 03:37
@dgordon562 is this solved? I am closing this issue for now.

**Closed by pb-jchin** 2016-10-17 03:37 UTC
Labels: question
