### ISSUE TITLE
Failed to run Falcon

### ISSUE THREAD

**Issue by emmanuelconstantino19** [PacificBiosciences/FALCON#403] opened 2016-07-01 07:06 UTC
I'm trying to run falcon but this error keeps on popping on my screen
```
make[1]: Leaving directory `/net/home/econstantino/WORK/FALCON-integrate/FALCON-examples/.git/git-sym-local/cache'
Traceback (most recent call last):
  File "/home/econstantino/WORK/FALCON-integrate/fc_env/bin/git-sym", line 455, in main
    cmd_table[cmd](**args)
  File "/home/econstantino/WORK/FALCON-integrate/fc_env/bin/git-sym", line 357, in git_sym_update
    retrieve(needed)
  File "/home/econstantino/WORK/FALCON-integrate/fc_env/bin/git-sym", line 284, in retrieve
    retrieve_using_make(makefilename, paths)
  File "/home/econstantino/WORK/FALCON-integrate/fc_env/bin/git-sym", line 277, in retrieve_using_make
    system(cmd)
  File "/home/econstantino/WORK/FALCON-integrate/fc_env/bin/git-sym", line 81, in system
    raise Exception('%d <- %r' %(rc, cmd))
Exception: 512 <- "make -j  -f /net/home/econstantino/WORK/FALCON-integrate/FALCON-examples/git-sym.makefile 'm140913_050931_42139_c100713652400000001823152404301535_s1_p0.1.subreads.fasta' 'm140913_050931_42139_c100713652400000001823152404301535_s1_p0.2.subreads.fasta'"

make: *** [setup-ecoli2] Error 1
```
do you have any idea on what the problem may be?

**Comment by pb-cdunn** [comment] 2016-07-01 17:08
The real cause of error is probably a git earlier on `stderr`, but you can try this:

    cd /net/home/econstantino/WORK/FALCON-integrate/FALCON-examples/.git/git-sym-local/cache
    make -j  -f /net/home/econstantino/WORK/FALCON-integrate/FALCON-examples/git-sym.makefile 'm140913_050931_42139_c100713652400000001823152404301535_s1_p0.1.subreads.fasta' 'm140913_050931_42139_c100713652400000001823152404301535_s1_p0.2.subreads.fasta'

**Comment by emmanuelconstantino19** [comment] 2016-07-04 06:57
Thank you very much! It worked.

**Comment by pb-cdunn** [comment] 2016-07-04 14:05
Well, I meant that you could run that in order to learn the cause of error, so we could see it. But if it's working for you now, great! I'll close this.

**Closed by pb-cdunn** 2016-07-04 14:05 UTC
