### ISSUE TITLE
great increase in disk space and run time between Nov 2015 and Feb 2016

### ISSUE THREAD

**Issue by dgordon562** [PacificBiosciences/FALCON#320] opened 2016-04-04 14:09 UTC
Hi, Chris,

This applies to the 0-rawreads daligner runs.  What used to take about 1 day now takes around 14 days.  What used to take about 1 to 3 TB of disk space now takes around 30 TB of disk space.  This has caused the disk to fill up, crashing programs on other projects and losing days of other people's work (and getting me in big trouble (grin)).   Any ideas of what made such a drastic change?  Was there a daligner, fasta2DB or dbsplit change in that period?  I will try to confirm by rerunning the same assembly with the Nov 2015 version of Falcon.

Anyone else seeing this same change in behavior?

Best wishes,
David

**Comment by pb-cdunn** [comment] 2016-04-04 14:55
It could be lots of things:

* log-files
  * If so, please tell us the most common output that you see.
* Undeleted .las files
  * But this cannot account for an order of magnitude.
* Increased number of daligner blocks and jobs.
  * This would be caused by a change in your own settings, most likely. But I think we made `DBsplit -a` the default. If you have lots of extra coverage from individual ZMWs, then `-a` could yield far too much raw coverage.
  * Can you compare before and after?

You'll have to scan your directories to figure out which files consume the most disk-space. After that, I'll help you to solve the problem.

(If the problem turns out to be `DBsplit -a`, then the solution is *not* to drop `-a`, but rather to start using our new auto-length-cutoff calculation. Of course, you would need to update to our latest code-base, which you should do anyway. Your customizations should no longer be needed.)

**Comment by dgordon562** [comment] 2016-04-04 17:17
I found the cause of part of the increase in disk space:

all of the job_*/rj_*.sub.sh

have:

#rm -f *.C?.las
#rm -f *.N?.las

(note the commented out).  You probably had these commented out for testing and forgot to remove them?

All of the disk space is taken up by las files in the job_ directories.

**Comment by pb-cdunn** [comment] 2016-04-04 20:41
When those files are merged, no data are lost. So that cannot possibly explain an order of magnitude increase in disk use. Not by itself.

Have you looked into how many blocks/jobs you had/have?

**Comment by dgordon562** [comment] 2016-04-04 21:22
You're right--this is just a factor of 2.  The increase in blocks is another factor of 2 to 2.5.  So there is another factor of 2 somewhere.

But isn't what I found (above) something that should be fixed?

**Comment by pb-cdunn** [comment] 2016-04-05 00:27
Yes, we will start deleting the extra .las files. I'll push that this week.

**Comment by aclum** [comment] 2016-04-06 16:32
The number of indoes has become a problem for us as well since we are running a large number of Falcon jobs.  Right now we trying to process several low input libraries so have to use a very length cutoff, 1kb. These are the parameters we are using 

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 1000

# The length cutoff used for seed reads used for pre-assembly
length_cutoff_pr = 1000

# overlapping options for Daligner
pa_HPCdaligner_option =  -v -dal4 -t8 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t8 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50


# error correction consensus option
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6

# overlap filtering options
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 5 --bestn 10


Any suggestions for modifications for ~40 MB fungal sized genomes that would reduce Inodes w/o compromising results?

**Comment by pb-cdunn** [comment] 2016-04-06 18:07
First, try this:
```
length_cutoff = -1
seed_coverage = 30
genome_size = 40000000
```

**Comment by pb-cdunn** [comment] 2016-04-06 18:09
>  Right now we trying to process several low input libraries so have to use a very length cutoff, 1kb

"Low accuracy" and "very low length cutoff"? (You can edit your post in GitHub. Just click on the "pencil".)

**Comment by pb-cdunn** [comment] 2016-05-19 00:54
Please re-open and clarify if still a problem.

**Closed by pb-cdunn** 2016-05-19 00:54 UTC
