### ISSUE TITLE
PypeFlow jobs failing intermittently

### ISSUE THREAD

**Issue by johnomics** [PacificBiosciences/FALCON#12] opened 2015-01-22 12:46 UTC
Two separate FALCON jobs have failed with very similar Tracebacks:

```
Traceback (most recent call last):
  File "/usr/local/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.2.1', 'fc_run.py')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-2.1-py2.7.egg/pkg_resources.py", line 488, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-2.1-py2.7.egg/pkg_resources.py", line 1338, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 738, in <module>
    wf.refreshTargets(updateFreq = wait_time) #all            
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 519, in refreshTargets
    self._refreshTargets(objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 649, in _refreshTargets
    task2thread[URL].join()
KeyError: 'task://localhost/m_00017_preads'
```

```
Traceback (most recent call last):
  File "/usr/local/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.2.1', 'fc_run.py')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-2.1-py2.7.egg/pkg_resources.py", line 488, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-2.1-py2.7.egg/pkg_resources.py", line 1338, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 653, in <module>
    wf.refreshTargets(updateFreq = wait_time) # larger number better for more jobs
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 519, in refreshTargets
    self._refreshTargets(objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/usr/local/lib/python2.7/dist-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 649, in _refreshTargets
    task2thread[URL].join()
KeyError: 'task://localhost/ct_00016'
```

In both cases the files for jobs 00017 / 00016 appeared to be complete, with no errors in the logs. Several other FALCON runs have completed without error (including an exact rerun of the second job).

I'm running on a single 64-core machine running Ubuntu 14.04. Concurrency settings for the second job:

```
pa_concurrent_jobs = 14
cns_concurrent_jobs = 14
ovlp_concurrent_jobs = 14
pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 4
```

**Comment by pb-jchin** [comment] 2015-01-24 17:51
John, I see this before sometimes in my runs. It is not 100% reproducible on my side. I will probably need to modify line 618-621 of `pypeflow/controller.py` to make it more robust. If you have any more information please let me know. Thank.

**Comment by johnomics** [comment] 2015-01-27 14:31
OK thanks - sorry, I'm not able to replicate this reliably either, it just happens every now and again. I'll let you know if I can track down the cause.

**Comment by pb-jchin** [comment] 2015-01-27 18:12
I may be able to find a couple way to make it more robust but since it maybe system related issue, it is harder to test.

**Comment by pb-jchin** [comment] 2015-03-02 15:20
johnomics, what kind of file system do you use?

**Comment by johnomics** [comment] 2015-03-09 08:48
ext4 on Ubuntu 14.04 (sorry for the delay, I have been away).

**Comment by flowers9** [comment] 2015-03-20 20:15
I'm also run across this, with functionally identical error messages.  My setup apears fairly different from johnomics, as I'm running with 9 8-core machines running Suse 13.1, with local software and data mounted over nfs3.

**Comment by pb-jchin** [comment] 2015-03-20 21:39
flower9, can you find any hint in the log files?  After some upgrade on our system, I don't this anymore

**Comment by flowers9** [comment] 2015-03-23 16:24
Where would the log file for the pypeFLOW bits be?  The stdout output is just the traceback, plus the one lines notes of jobs being submitted to grid, and the *.log files in the various directories don't seem to contain any of the logger info that pypeFLOW seems capable of generating.

When you mention upgrading, is that upgrading your OS, or upgrading falcon?

**Comment by flowers9** [comment] 2015-03-23 16:28
When you say update, do you mean updating falcon, or updating your OS (or something else)?

As for error messages, other than the stdout output (which just has the traceback and grid job submissions), I'm not sure where to look.  The various *.log files don't seem to contain anything useful - I don't see any of the output from the logger calls in pypeFLOW's controller.py code.

**Comment by pb-jchin** [comment] 2015-03-23 17:35
Our "update" involves multiple things. I used to run Falcon in a fragile luster setup and I saw a lot of problem.  Once we changed the OS to CentOS  from Ubuntu (which has un-supported luster client) and re-architect some hardware to have dedicate luster cluster, the problems all go away.  

I think what happens is the some file creation and modification is not sync properly through the clusters. When I developed Pypeflow a couple years ago, I had a problem with our NFS system then.  A file created by one computation node would not be appeared in another one.  An workaround was implemented by forcing to do fstat (through "ls") to get most up-to-date file system view.  `pypeFLOW` was designed to use filesystem as a synchronization mechanism (e.g., like "Make").  An alternative way will be implementing the synchronization mechanism through database (with ACID property) and/or some message queue system.  That will make the whole thing more heavy weight though.

**Comment by pb-jchin** [comment] 2015-03-23 17:38
flower9, how big is your data?  I can try to see whether it is possible to reproduce it on my side.

**Comment by flowers9** [comment] 2015-03-25 14:59
I agree that is looks a lot like a race issue, and if you're using file locks then that does seem like a likely cause.  Personally, I use directory locks as directories seem to be handled better by nfs, although I haven't written anything as complex as falcon, so I don't know how it would hold up.

I've got about 12G of data, but I'd have to check if I could release it.  In any case, it's still an inconsistent problem - a second run ran just fine.

**Comment by bryantdo** [comment] 2015-03-26 20:20
Hey guys,

Any progress on this issue? I'm seeing similar traces:

```javascript
Traceback (most recent call last):
  File "/home/dbryant/bin/pacbio_falcon/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.2.1', 'fc_run.py')
  File "/home/dbryant/bin/pacbio_falcon/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbryant/bin/pacbio_falcon/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/shares/tmockler_share/dbryant/bin/pacbio_falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 653, in <module>
    wf.refreshTargets(updateFreq = wait_time) # larger number better for more jobs
  File "/home/dbryant/bin/pacbio_falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 519, in refreshTargets
    self._refreshTargets(objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/home/dbryant/bin/pacbio_falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 649, in _refreshTargets
    task2thread[URL].join()
KeyError: 'task://localhost/ct_00121'
```

**Comment by pb-jchin** [comment] 2015-03-26 21:27
@bryantdo, yes if you move to local, you should have less of this problem.    One possibility, if you can confident to modify the driving code, you can submit the jobs using blocking mode "qsub -y" and create those tracking file locally. However, this solution will have other problem.

**Comment by bryantdo** [comment] 2015-03-26 21:55
@pb-jchin Thanks for your reply, I'll try moving to local.

Is there any chance that I can resume the pipeline where it died? Or must I start over?

**Comment by pb-jchin** [comment] 2015-03-26 21:57
@bryantdo yes, the code is designed to be restart-able. It is kinda modeled after the command "make". If some dependences are not satisfied, the code will pick up what needed to be done to get the target.

**Comment by bryantdo** [comment] 2015-03-26 21:59
@pb-jchin Okay great, thanks Jason. I'll try executing the pipeline again.

**Comment by bryantdo** [comment] 2015-03-27 05:33
@pb-jchin After restarting the pipeline I get another crash with trace:

```
Traceback (most recent call last):
  File "/fc_env/bin/fc_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-kit==0.2.1', 'fc_run.py')
  File "/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 696, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/pacbio_falcon/fc_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1614, in run_script
    exec(code, namespace, namespace)
  File "/pacbio_falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 738, in <module>
    wf.refreshTargets(updateFreq = wait_time) #all
  File "/pacbio_falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 519, in refreshTargets
    self._refreshTargets(objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/pacbio_falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 649, in _refreshTargets
    task2thread[URL].join()
KeyError: 'task://localhost/d_d9d5103a_preads'
```

After executing the pipeline a third time, it finishes but with odd results. all files in in the directory 2-asm-falcon like a_ctg* are of size 0. The files like p_ctg* are not of size 0, but they are small.

Any ideas?

**Comment by pb-jchin** [comment] 2015-03-27 05:34
How big is your genome? For small one, you can use local mode.

**Comment by bryantdo** [comment] 2015-03-27 05:35
@pb-jchin It is a large plant genome of around 760 Mbp.

**Comment by pb-jchin** [comment] 2015-03-27 05:41
Well, you might need to figure out a better cluster system (maybe in the same hardware but different configuration,etc.) for 760Mb genomes. I think the filesystem is not abel to sync the process correctly. (This is very hard for me to debug as this is system dependent. You will need some good software developer and system admin to figure out a solution. I have to do the same thing here too.)   Maybe you can contact some PacBio FAS, they might be able to give some advise.  You can try cloud service provided by third party too.

**Comment by pb-jchin** [comment] 2015-03-27 18:23
I am not sure whether this will help as I can't reproduce that easily.

The relevant code is 

https://github.com/pb-jchin/pypeFLOW/blob/master/src/pypeflow/controller.py  (last commit/7ccce7d08280c38549b6cdac76005656d1248d20)

line 619-625
```
t.start()
task2thread[URL] = t
```
any thread "URL" (resource name for a task name) should be inserted in the `task2thread` dictionary.  I have yet to understand why some of the URL seems to be missing later.  However, you could swap the line to see if it helps.

**Comment by bryantdo** [comment] 2015-03-27 18:25
Okay thanks. I'm setting this up to run on AWS, may have better NFS performance compared to our local cluster. I'll also try your suggested change.

**Comment by pb-jchin** [comment] 2015-03-27 20:44
I tried to see if I can get some of our people who has experience setting it up on AWS to help.

**Comment by bryantdo** [comment] 2015-03-27 20:52
Thanks @pb-jchin, I already have it working on AWS though. Currently assembling the test ecoli data, I'll let you know how it goes once I move on to our real dataset.

**Comment by pb-jchin** [comment] 2015-03-27 20:54
yes. but I/O will be still an issue on AWS. Will you consider using DNAnexus for this?

**Comment by bryantdo** [comment] 2015-03-27 20:55
I would think I/O would be better though, I'm using only SSD-class disk. If it seriously becomes an issue I can set up a raid0 array. 

Doesn't DNAnexus use AWS anyway?

**Comment by lhon** [comment] 2015-03-27 20:58
FYI Amazon announced some new features for EBS volumes the other day—up to 16 TB volumes and 20k IOPS:

https://aws.amazon.com/blogs/aws/now-available-16-tb-and-20000-iops-elastic-block-store-ebs-volumes/

Are you using StarCluster to set up multiple nodes?

**Comment by bryantdo** [comment] 2015-03-27 21:00
@pb-jchin I'm using only local storage for data processing.

@lhon Yes I am using Starcluster, with a custom Ubuntu 14.04 image. Thanks for the heads up on the EBS upgrades. I'll provision a working disk using the upgraded type.

**Comment by bryantdo** [comment] 2015-03-28 23:01
@pb-jchin @lhon Hey guys, getting similar errors using AWS. This is on one machine using local SSD class storage (not over NFS), trying to assemble the test ecoli data. Completely fresh install of the FALCON suite.

````
...
Your job 111 ("m_00006_preads-53d4c38a") has been submitted
Your job 112 ("m_00003_preads-53d50070") has been submitted
Your job 113 ("m_00004_preads-53d53716") has been submitted
Your job 114 ("m_00002_preads-53d56542") has been submitted
Your job 115 ("m_00001_preads-53d5636c") has been submitted
Your job 116 ("m_00005_preads-53d5a548") has been submitted
Traceback (most recent call last):
  File "/software/pacbio_falcon/fc_env/bin/fc_run.py", line 5, in <module>
    pkg_resources.run_script('falcon-kit==0.2.1', 'fc_run.py')
  File "/software/pacbio_falcon/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/software/pacbio_falcon/fc_env/lib/python2.7/site-packages/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/software/pacbio_falcon/fc_env/lib/python2.7/site-packages/falcon_kit-0.2.1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fc_run.py", line 738, in <module>
    wf.refreshTargets(updateFreq = wait_time) #all
  File "/software/pacbio_falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 519, in refreshTargets
    self._refreshTargets(objs = objs, callback = callback, updateFreq = updateFreq, exitOnFailure = exitOnFailure)
  File "/software/pacbio_falcon/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/controller.py", line 649, in _refreshTargets
    task2thread[URL].join()
KeyError: 'task://localhost/m_00002_preads'
````

````
root@master:/software/pacbio_falcon/ecoli_test# find . -name "m_00002*"
./sge_log/m_00002_preads-53d56542.o114
./sge_log/m_00002_preads-53d56542.po114
./sge_log/m_00002_raw_reads-5056aeb6.po92
./sge_log/m_00002_raw_reads-5056aeb6.o92
./1-preads_ovl/m_00002
./1-preads_ovl/m_00002/m_00002.sh
./1-preads_ovl/m_00002/m_00002_done
./0-rawreads/m_00002
./0-rawreads/m_00002/m_00002.sh
./0-rawreads/m_00002/m_00002_done
````

**Comment by pb-jchin** [comment] 2015-03-28 23:46
Can you share your image and instance setup? I like to see if I can reproduce it on AWS.

**Comment by bryantdo** [comment] 2015-03-29 00:32
Sure. If you give me your AWS account ID I will share the image with you. I launch the instance(s) via Starcluster. In the above case I am using c3.4xlarge instance type.

**Comment by pb-jchin** [comment] 2015-03-29 05:05
Ok. there is a possibility that some of the previous "refreshTarget" call actually did not finish with all threads are joined. The `task2thread` is a local method variable of `PypeThreadWorkflow._refreshTargets`. If the previous call of `refreshTarget` has some threads that do not terminated, the second call will have a thread job which URL is not in the `refreshTarget` directory.  It is possible the previous did not finished successfully.     Do you see the file `p_merge_done` in `1-preads_ovl` directory?

**Comment by pb-jchin** [comment] 2015-03-29 05:15
If you want to have temporary workaround, you can change the `task2thread` to be a instance variable. (add `self.` before all `task2thread` variable  inside `PypeThreadWorkflow._refreshTargets()`) However, the right thing to do it to make sure all `PypeThreadWorkflow._refreshTargets()` return `True`. If not, some jobs may not finish successfully, the process should be terminated.

**Comment by pb-jchin** [comment] 2015-03-30 04:08
@bryantdo if you have a chance, can you turn on the logging by modify the line `log = 0` in `fc_run.py` to `log = True` and run it again?  The log is sent to `stderr`. Paste the log (it could be big) to gist or DropBox.  This might help me to see what is going on... (I am trying to test if I can manually introduce such error, but not with much success yet.)

**Comment by pb-jchin** [comment] 2015-03-30 17:10
@bryantdo I get a log the myself.  Ok, the problem is indeed a race condition.

Here is the problematic line:
```
613             if numAliveThreads == 0 and len(jobsReadyToBeSubmitted) == 0: #better job status detection, using "running" status rather than checking the thread lib?
614                 break
```

(I had a comment before knowing this could be a problem.. Ha)  

What happens is that the last thread is finished and trigger this condition. However, the message queue communicating between the worker thread and the host is not cleared up.  The left over message is picked up for the next `_refreshTarget` calls.  

I will need some time to think about right patch.  Stay tuned.

**Comment by bryantdo** [comment] 2015-03-30 17:11
@pb-jchin Okay thanks for the info. I was working through my response but now I'll wait to hear back from you.

**Comment by pb-jchin** [comment] 2015-03-30 18:15
@bryantdo please try https://github.com/pb-jchin/pypeFLOW issue12 branch. (git clone and git branch) to test the fix out. I am doing an independent test too. Thanks. If it works, I will merge it into the master branch.

**Comment by bryantdo** [comment] 2015-03-30 19:36
@pb-jchin Okay trying now.

**Comment by pb-jchin** [comment] 2015-03-30 23:27
@bryantdo let me know if it goes through so I might be able to close this issue. Thanks.

**Comment by bryantdo** [comment] 2015-03-31 16:43
@pb-jchin Assembling the sample ecoli data finished without any errors, I'm working on my real (large) data now.

**Comment by pb-jchin** [comment] 2015-03-31 16:45
@bryantdo great, I am closing this bug and merge the issue12 to master.  I still recommend to chat with someone who has experience doing large PacBio assembly on AWS. One of PacBio bioinformatics had set it up and did a 1G assembly.  There are still some technical things that need some care. Thanks a lot.

**Closed by pb-jchin** 2015-03-31 16:45 UTC
Labels: bug

**Comment by bryantdo** [comment] 2015-03-31 16:47
@pb-jchin Sure, I'd be happy to discuss this. Who would be a good person to contact?

**Comment by pb-jchin** [comment] 2015-03-31 16:49
@bryantdo @lhon many be able to give some general guidance. This is not official supported, but we do like to share some of our own experience.

**Comment by bryantdo** [comment] 2015-04-03 03:39
Hey guys,

Well my large data set finished assembling with falcon, no errors or restarts. Unfortunately all of the c_ctg* files are of size 0, and p_ctg.fa is way too small. Any ideas?

**Comment by mseetin** [comment] 2015-04-03 04:17
What was your choice of min_cov in overlap_filtering_setting?

**Comment by bryantdo** [comment] 2015-04-03 04:20
min_cov = 20

**Comment by mseetin** [comment] 2015-04-03 04:26
Yeah, that's much too high for most systems.  It's really only appropriate for the E. coli example, where there is tremendous coverage.  In the other examples provided, such as the cfg files for Arabadopsis or Drosophila, min_cov is in the 2-5 range.  This parameter sets the minimum number of overlapping pre-assembled reads that must be present to make a contig.  If you started with, say, 30x coverage in raw reads, it's actually really unlikely you'll have 20x coverage in preassembled reads at that step, except in your highest coverage regions (the ones that are in your final assembly).  The good news is that you can run the late stages of the assembly without having to rerun the preassembly step again (preassembly is the most time consuming).

**Comment by bryantdo** [comment] 2015-04-03 04:27
Great, I'll set this to 2-5. Can I just re-execute the pipeline? Or is there something special I need to do in order to restart it at the correct step?

**Comment by mseetin** [comment] 2015-04-03 04:34
Since these calculations are pretty fast, you can experiment with a range of values for this.  Choosing 5 or 7 or so will minimize the risk of misassembly, but you might not connect some contigs you have data that show should be connected.  Choosing 2 or even one will maximize the lengths of your contigs, but you have a higher risk of missassembling contigs based on sparse data.  What you can do is make separate directories for each trial, make new cfg files for in each directory, change the input type in the cfg file from "raw" to "preads," and make a new fofn that points to the .fa files in the 0-raw-reads/preads/ directory in the directory of your current job.  That way, you can evaluate the results of different choices of min_cov and preserve the results of each.

**Comment by bryantdo** [comment] 2015-04-03 04:36
Awesome, thanks.
