### ISSUE TITLE
fasta2DB error

### ISSUE THREAD

**Issue by conte1** [PacificBiosciences/FALCON#132] opened 2015-07-09 20:45 UTC
Hi,

I'm getting the error below running falcon on the test e. coli data. I'm using the new v0.3.0 integration.

```
fasta2DB -v preads -f/lustre/mconte/FALCON/examples/ecoli_test/1-preads_ovl/input_preads.fofn
Adding 'out.00001' ...
File out.00001.fasta, Line 1: Pacbio header line format error
```

I don't think this is the same as issue #27 , but maybe I'm missing something.

Thanks,
Matt

**Comment by pb-jchin** [comment] 2015-07-09 20:54
you might not have `--output_dformat`  for the `falcon_sense_option` in the configuration file.  Do you use  the updated E. coli example configuration file?

**Comment by pb-jchin** [comment] 2015-07-13 22:19
@conte1 have you tried `--output_dformat`?

**Comment by conte1** [comment] 2015-07-14 01:05
Yeah, adding `--output_dformat` fixed that error. I was having some other issues so I hadn't responded yet, but they seem to be unrelated and I think I've figured them out. So I think you can close this issue. Thanks.

**Comment by outpaddling** [comment] 2015-08-21 14:43
You might want to add this to the example shown at

https://github.com/PacificBiosciences/FALCON/wiki/Setup%3A-Running

so that others don't trip on it in the future.

Cheers,

    Jason

**Comment by pb-cdunn** [comment] 2015-08-21 16:05
`--output_dformat` is deprecated, as it is now the default.

**Comment by outpaddling** [comment] 2015-08-21 21:05
That's odd...  As of when?   We're running a snapshot of FALCON-integrate and its submodules from Aug 17th.

Do you know what else might trigger this error?

Thanks...

**Comment by pb-cdunn** [comment] 2015-08-22 00:26
You need to post your run.cfg. If FALCON generates preads from raw-reads, then the defaults should work. If you are starting with preads, then the problem is in your own headers.

**Comment by outpaddling** [comment] 2015-08-22 13:45
Well, adding --output_dformat seems to have fixed the issue.  The first 
attempt finished processing the raw reads and failed immediately at the 
beginning of the next step with

File out.00001.fasta, Line 1: Pacbio header line format error

The first line of this file was just ">00000000" or something similar.

After adding --output_dformat, it completed the second step without 
errors and populated the 1-preads_ovl directory.

The first line of the out.00001.fasta is now ">prolog/000000000/0_2180".

Our cfg file:

[General]
# list of files of the initial subread fasta files
input_fofn = input.fofn

job_type = local
# job_type = SLURM

# FIXME: Is there a way to reduce chatter from pypeflow?
# FIXME: How do we control the number of threads in each job?
input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000

# Cluster queue setting
sge_option_da =
sge_option_la =
sge_option_pda =
sge_option_pla =
sge_option_fc =
sge_option_cns =

# concurrency settgin
pa_concurrent_jobs = 7
cns_concurrent_jobs = 7
ovlp_concurrent_jobs = 7

# overlapping options for Daligner
pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

# error correction consensus optione
falcon_sense_option = --output_dformat --output_multi --min_idt 0.70 
--min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6

# overlap filtering options
overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 
--bestn 10

**Comment by pb-cdunn** [comment] 2015-08-22 15:20
I wish I knew which program needed it and what version. That option is literally ignored now. That's easily verified by grepping. Can you at least tell me the commit of FALCON?

    cd FALCON
    git rev-parse HEAD

**Comment by outpaddling** [comment] 2015-08-24 15:12
I reran the analysis from the beginning without the dformat, just to make sure I wasn't using old data from the first step, flag and it did die again with the same error.

I then ran the commands below for both the rev used by my current packages and a fresh download from this morning.  The grep results were the same: It looks like consensus.py has it dformat off by default.

FreeBSD sculpin.acadix  bacon ~/Prog/Ports/Src/PBFalcon/FALCON-integrate-2015.08.24 433: git rev-parse HEAD
c6dd28d88fe28abe4b0719f3e50a0ea784d188ef

FreeBSD sculpin.acadix  bacon ~/Prog/Ports/Src/PBFalcon/FALCON-integrate-2015.08.24 434: git submodule
 dc506e67938c1c923ebb7e43ff8ce32ec923d8ba DALIGNER (remotes/origin/gm-master-10-gdc506e6)
 337a0ee0e77624094221577bdaa38c79b5444d91 DAZZ_DB (remotes/origin/gm-master-7-g337a0ee)
 d3939f2a4a5daaaa6090e1b386668c9c91d94f8e FALCON (0.2JASM-205-gd3939f2)
 97aecd0a69f62e3029bd5fd233ff9cceccd42bce FALCON-examples (heads/master)
 215e8cfcdda412258daff3b689cc7d0daeca4e47 FALCON-make (heads/master)
 483836854e1bafb6e40cf17f3a9382efe351daad git-sym (heads/master)
 a6751fac8aa575b130c558488af0532f47cf8999 pypeFLOW (v0.1.0-42-ga6751fa)
 8e9cb4a7c34a12762a0ef8b2c5003ded4346cd49 virtualenv (13.0.3-9-g8e9cb4a)

FreeBSD sculpin.acadix  bacon ~/Prog/Ports/Src/PBFalcon/FALCON-integrate-2015.08.24 435: find . -type f -exec fgrep -l dformat '{}' \;
./FALCON/examples/fc_run_CHM1_P6.cfg
./FALCON/examples/fc_run_LG.cfg
./FALCON/examples/fc_run_arab.cfg
./FALCON/examples/fc_run_dmel.cfg
./FALCON/examples/fc_run_ecoli.cfg
./FALCON/examples/fc_run_ecoli_2.cfg
./FALCON/src/py/mains/consensus.py
./FALCON-examples/run/arab/fc_run.cfg
./FALCON-examples/run/ecoli/fc_run.cfg
./FALCON-examples/run/ecoli2/fc_run.cfg
./FALCON-examples/run/lambda-hgap/fc_run.cfg
./FALCON-examples/run/lambda/fc_run.cfg
./FALCON-examples/run/synth0/fc_run.cfg

FreeBSD sculpin.acadix  bacon ~/Prog/Ports/Src/PBFalcon/FALCON-integrate-2015.08.24 436: grep -C 5 dformat ./FALCON/src/py/mains/consensus.py
                        help='trim the input sequence with k-mer spare dynamic programming to find the mapped range')
    parser.add_argument('--output_full', action="store_true", default=False,
                        help='output uncorrected regions too')
    parser.add_argument('--output_multi', action="store_true", default=False,
                        help='output multi correct regions')
    parser.add_argument('--output_dformat', action="store_true", default=False,
                        help='output daligner compatible header, only work with --output_multi')
    parser.add_argument('--min_idt', type=float, default=0.70,
                        help='minimum identity of the alignments used for correction')
    parser.add_argument('--edge_tolerance', type=int, default=1000,
                        help='for trimming, the there is unaligned edge leng > edge_tolerance, ignore the read')
--
            if args.output_multi == True:
                seq_i = 0
                for cns_seq in cns:
                    if len(cns_seq) < 500:
                        continue
                    if args.output_dformat:
                        if seq_i >= 10:
                            break
                        print ">prolog/%s%01d/%d_%d" % (seed_id, seq_i, 0, len(cns_seq))
                        print format_seq(cns_seq, 80)
                    else:

**Comment by pb-cdunn** [comment] 2015-08-24 16:18
Oh. I see.

@pb-jchin, We need a new release of FALCON-integrate with the change of default for output-format.

**Comment by pb-jchin** [comment] 2015-08-24 16:37
@pb-cdunn  I am thinking about a tag v0.4 release

**Comment by pb-jchin** [comment] 2015-10-23 20:57
v0.4 and v0.4.1 are tagged.  the `dformat` is default and close this now.

**Closed by pb-jchin** 2015-10-23 20:57 UTC
Labels: invalid
