### ISSUE TITLE
Is it possible to run FALCON on single machine?

### ISSUE THREAD

**Issue by Reedwarbler** [PacificBiosciences/FALCON#276] opened 2016-01-26 00:55 UTC
Hi,

I just wonder can I run FALCON on a single machine (with enough memory and cores), but not a cluster? I have successfully installed Falcon-Integrate but it will reports "qsub" command not found, as it only a single server not a cluster.  Thank you.

Best,
Chong

**Comment by pb-cdunn** [comment] 2016-01-26 01:47
In the `.cfg` file (provided as `fc_run.py foo.cfg`), use

    job_type=local

**Comment by Reedwarbler** [comment] 2016-01-26 02:41
Thank you for the reply.

Now it can run on a local server now. However, report errors when run the ecoli example (default config file):

2016-01-26 02:21:22,216 - pypeflow.task - ERROR - PypeTaskBase failed:
{'__class__.__name__': 'PypeThreadTaskBase',
 '_status': 'TaskInitialized',
 'inputDataObjs': {'rdb_build_done': PypeLocalFile('file://localhost/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/rdb_build_done', '/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/rdb_build_done')},
 'mutableDataObjs': {},
 'outputDataObjs': {'job_done': PypeLocalFile('file://localhost/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/job_0034/job_0034_done', '/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/job_0034/job_0034_done')},
 ....................
Traceback (most recent call last):
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 341, in __call__
    return self.runInThisThread(*argv, **kwargv)
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 362, in runInThisThread
    self.run(*argv, **kwargv)
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 276, in run
    rtn = self._runTask(self, *argv, **kwargv)
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/pypeflow-0.1.1-py2.7.egg/pypeflow/task.py", line 190, in _runTask
    return self._taskFun(self)
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 263, in task_run_daligner
    job_type=config['job_type'], sge_option=config['sge_option_da'])
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 144, in run_script_and_wait_and_rm_exit
    job_type, sge_option)
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 137, in run_script_and_wait
    run_script(job_data, job_type)
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 96, in run_script
    rc = _run_script(job_data)
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 66, in _run_script_local
    system(cmd, check=True)
  File "/data2/chongchu/tools/FALCON-integrate/fc_env/lib/python2.7/site-packages/falcon_kit-0.4.0-py2.7-linux-x86_64.egg/falcon_kit/mains/run.py", line 23, in system
    raise Exception(msg)
Exception: Call 'bash /data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/job_0034/rj_0034.sh 1> /data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/job_0034/rj_0034.sh.log 2>&1' returned 32256.

Any comments will be appreciate.

**Comment by pb-cdunn** [comment] 2016-01-26 04:57
Look in `/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/job_0034/rj_0034.sh.log`. You might need to adjust your settings.

It should also be possible to re-run `/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/job_0034/rj_0034.sh` and repeat the problem. You might isolate it that way.

**Comment by Reedwarbler** [comment] 2016-01-26 05:57
rj_0034.sh.log shows "/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/job_0034/rj_0034.sh: ./rj_0034.sub.sh: /bin/bash: bad interpreter: Text file busy".

But re-run rj_0034.sh no error happen.

**Comment by Reedwarbler** [comment] 2016-01-26 06:26
Clean everything and re-run, in the final statistic shows 5 failures and 15 success. And seems the same error: "/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/m_00001/rp_00001.sh: ./rp_00001.sub.sh: /bin/bash: bad interpreter: Text file busy". 

Any suggestions will be appreciate :>

**Comment by pb-cdunn** [comment] 2016-01-26 12:45
> /bin/bash: bad interpreter: Text file busy

This happens when one process creates an executable script (typically in NFS), sets the executable bit, and starts another process to execute it, but the second process doesn't see the executable bit yet. It's an NFS caching problem which occurs on some systems.

But this was fixed. What version of FALCON-integrate are you using? FALCON too. Post the result of running the following commands:
```sh
cd DIRECTORYWHEREYOUCLONED FALCON-integrate
cd FALCON-integrate
git rev-parse HEAD
cd FALCON
git rev-parse HEAD
```
Also, please post the contents of these:

* `/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/m_00001/rp_00001.sh`

* `/data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/m_00001/rp_00001.sub.sh`

In my own example, I see these:
```sh
export PATH=/home/UNIXHOME/cdunn/repo/gh/FALCON-integrate/fc_env/bin:/home/UNIXHOME/cdunn/repo/gh/FALCON-integrate/fc_env/bin:/home/UNIXHOME/cdunn/scr:/home/UNIXHOME/cdunn/local/bin:/home/UNIXHOME/cdunn/repo/gopath/bin:/home/UNIXHOME/cdunn/local/go/bin:/home/UNIXHOME/cdunn/scr:/home/UNIXHOME/cdunn/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:${PATH}
export PYTHONPATH=:${PYTHONPATH}
export LD_LIBRARY_PATH=:${LD_LIBRARY_PATH}

set -vex
cd /home/UNIXHOME/cdunn/repo/gh/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/m_00001
trap 'touch /home/UNIXHOME/cdunn/repo/gh/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/m_00001/m_00001_done.exit' EXIT
ls -il rp_00001.sub.sh
hostname
ls -il rp_00001.sub.sh
time /bin/bash ./rp_00001.sub.sh
touch /home/UNIXHOME/cdunn/repo/gh/FALCON-integrate/FALCON-examples/run/synth0/0-rawreads/m_00001/m_00001_done
```
```sh
#!/bin/bash
set -vex
LAmerge -v raw_reads.1 L1.1.1 L1.1.2 ; rm L1.1.1.las L1.1.2.las
mkdir -p ../las_files
ln -sf ../m_00001/raw_reads.1.las ../las_files
ln -sf ./m_00001/raw_reads.1.las ..
```
In the 2nd script, even though it has a shebang, by default we don't execute it directly. So in neither case should your error ever occur. For that reason, I suspect that your code is far out-of-date.

**Comment by Reedwarbler** [comment] 2016-01-26 19:50
Thank you for the reply.

FALCON-integrate version: cd9e9373a9f897bc429ecf820809c6d773ee5c44
FALCON version: 5942bc00d509e1b530c986a41eb13dc87b8fe5bb
I think should be the latest version, as I download by "git clone git://github.com/PacificBiosciences/FALCON-integrate.git" yesterday.


rp_00001.sh content:

export PATH=/data2/chongchu/tools/FALCON-integrate/fc_env/bin:/data2/chongchu/tools/DALIGNER-master:/data2/chongchu/tools/fermi-master:/home/.local/bin:/data2/chongchu/tools/bwa-0.7.12:/data2/chongchu/tools/bowtie2-2.2.6:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:${PATH}
export PYTHONPATH=:${PYTHONPATH}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib:${LD_LIBRARY_PATH}

set -vex
cd /data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/m_00001
trap 'touch /data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/m_00001/m_00001_done.exit' EXIT
ls -il rp_00001.sub.sh
hostname
chmod +x rp_00001.sub.sh
touch rp_00001.sub.sh
ls -il rp_00001.sub.sh
time ./rp_00001.sub.sh
touch /data2/chongchu/tools/FALCON-integrate/FALCON-examples/run/ecoli/0-rawreads/m_00001/m_00001_done


rp_00001.sub.sh content:

#!/bin/bash
set -vex
LAmerge -v raw_reads.1 L1.1.1 L1.1.2 L1.1.3 L1.1.4 L1.1.5 L1.1.6 L1.1.7 L1.1.8 L1.1.9 L1.1.10 L1.1.11 L1.1.12 L1.1.13 L1.1.14 L1.1.15 L1.1.16 L1.1.17 L1.1.18 L1.1.19 L1.1.20 ; rm L1.1.1.las L1.1.2.las L1.1.3.las L1.1.4.las L1.1.5.las L1.1.6.las L1.1.7.las L1.1.8.las L1.1.9.las L1.1.10.las L1.1.11.las L1.1.12.las L1.1.13.las L1.1.14.las L1.1.15.las L1.1.16.las L1.1.17.las L1.1.18.las L1.1.19.las L1.1.20.las
mkdir -p ../las_files
ln -sf ../m_00001/raw_reads.1.las ../las_files
ln -sf ./m_00001/raw_reads.1.las ..

**Comment by pb-cdunn** [comment] 2016-01-26 20:54
Interesting. In the past when this problem has occurred, it was related to the eXecution bit. But in your case, the script is run by bash. So the sub-process simply does not see the file yet.

Please post your `.cfg` (passed to **fc_run.py** on the command-line). That can narrow down the problem.

**Comment by Reedwarbler** [comment] 2016-01-26 21:04
I simply use the default one (only change the job_type ) in the example. These are the .cfg content:

[General]
job_type = local

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 12000

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 12000

avoid_text_file_busy=false

jobqueue = production
sge_option_da = -pe smp 8 -q %(jobqueue)s
sge_option_la = -pe smp 2 -q %(jobqueue)s
sge_option_pda = -pe smp 8 -q %(jobqueue)s
sge_option_pla = -pe smp 2 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s

pa_concurrent_jobs = 32
ovlp_concurrent_jobs = 32

pa_HPCdaligner_option =  -v -dal4 -t16 -e.70 -l1000 -s1000
ovlp_HPCdaligner_option = -v -dal4 -t32 -h60 -e.96 -l500 -s1000

pa_DBsplit_option = -x500 -s50
ovlp_DBsplit_option = -x500 -s50

falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --local_match_count_threshold 2 --max_n_read 200 --n_core 6 --output_dformat

overlap_filtering_setting = --max_diff 100 --max_cov 100 --min_cov 20 --bestn 10 --n_core 24

**Comment by pb-cdunn** [comment] 2016-01-26 21:48
Ok. I guess we need to add a delay, or at least a retry, in case of a slow local filesystem.

For now, since you're running locally, you can run completely in `/tmp`. You won't have an issue there.

**Comment by Reedwarbler** [comment] 2016-01-26 22:52
Sorry, I do not quite get your suggestion. I need to re-install FALCON-integrate under /tmp, and run the program?

**Comment by pb-cdunn** [comment] 2016-01-26 23:02
No, just run from a different directory. The current installation will still be in your `PATH`.

    mkdir /tmp/me
    cp fc_run.cfg /tmp/me
    cd /tmp/me
    fc_run.py fc_run.cfg

You don't even have to copy fc_run.cfg if you don't want.

**Comment by Reedwarbler** [comment] 2016-01-26 23:43
It's wired. I still met the same problem by running under /tmp. Let me try on a different server and let you know.

**Comment by pb-cdunn** [comment] 2016-01-27 00:04
At this point, I think you need to debug it. It's possible that you are in a virtual machine, so /tmp is the same as anywhere.

I'll provide a retry tomorrow.

**Comment by philippbayer** [comment] 2016-02-16 08:03
Hello, I've now encountered apparently the exact same issue trying FALCON on a NFS directory in a non-SGE (PBS) cluster with the *E. coli* test data, sadly I can't access any local /tmp. 

My .cfg file looks pretty much like @Reedwarbler's using `job_type = local`. 

It crashes with `Exception: Call 'bash /gpfs1/scratch/30days/pbayer/FALCON-integrate/ecoli_test/0-rawreads/m_00006/rp_00006.sh 1> /gpfs1/scratch/30days/pbayer/FALCON-integrate/ecoli_test/0-rawreads/m_00006/rp_00006.sh.log 2>&1' returned 32256.` and when I look into the log, I get 

```
time ./rp_00006.sub.sh
+ ./rp_00006.sub.sh
/gpfs1/scratch/30days/pbayer/FALCON-integrate/ecoli_test/0-rawreads/m_00006/rp_00006.sh: ./rp_00006.sub.sh: /bin/bash: bad interpreter: Text file busy
```

One workaround could be to run `sync` to force write to the NFS disk before `time ./rp_00006.sub.sh` is run, currently trying to find out which sub-script writes these .sh files so I can test that for myself.

And:
```
FALCON-integrate> git rev-parse HEAD
cd9e9373a9f897bc429ecf820809c6d773ee5c44
/FALCON-integrate> cd FALCON
/FALCON> git rev-parse HEAD
5942bc00d509e1b530c986a41eb13dc87b8fe5bb 
```

**Comment by pb-cdunn** [comment] 2016-02-16 12:53
We already have a work-around:
```
* 9a3cc0e Address 'Text file busy' problem
* b829e68 Rm old debug
*   5942bc0 Merge pull request #266 from pb-cdunn/stop_all_jobs_on_failure
```
I'm updating PacificBiosciences/FALCON-integrate#33, but I wish that change weren't necessary. Before you pull, could you try `sleep 70`? NFS is often configured with a 60s refresh. The problem is that the process which creates the file has not yet closed it ("5w" => fd-5 open for write) *from the point-of-view of another process*. Apparently, NFS is slow to update the states of file-descriptors.

The work-around is to run `bash foo.exe` instead of `./foo.exe`. The downside is that `bash` becomes the name of the process.

**Comment by philippbayer** [comment] 2016-02-16 14:23
I can confirm that it works fine with `sleep 70`

I didn't want to touch the `./foo` structure since the comment sounded so ominous: `# We use shebang + chmod so we can see the sub-script in 'top'.`, sounded like there was some other unknown process patched into that for some reason, I can see from your commit that this isn't the case :)

**Comment by pb-cdunn** [comment] 2016-02-16 15:41
Nope. Nothing ominous. We do *not* depend on the process name at all. It's just annoying to see a large list of "bash" procs.

Eventually, we'll have a file which maps pid to command, and we'll have a program which can report which ones are still running and can kill specific sets. So I'm fine with the change. (Hopefully you've already updated FALCON. You can update FALCON-integrate too if you want.) Closing.

**Closed by pb-cdunn** 2016-02-16 15:41 UTC

**Comment by philippbayer** [comment] 2016-02-17 02:34
I can confirm that it doesn't crash due to `Text file busy` after updating everything, thank you very much for your fast help!

**Comment by pb-cdunn** [comment] 2016-02-17 02:37
Glad to help! And we'll have a better solution before too long...
